data_root_dir: 'output/feat_dir'
results_dir: 'results'
save_exp_code: 'None'
models_exp_code: 'exp_s1'
splits_dir: null
model_size: 'small'
model_type: 'clam_sb'
drop_out: false
k: 10
k_start: -1
k_end: -1
fold: -1
micro_average: false
split: 'test'
task: 'task_1_tumor_vs_normal'
csv : dataset_csv/label.csv
