data_root_dir: output/feat_dir
max_epochs: 200
lr: !!float 1e-4
label_frac: 1.0
reg: !!float 1e-5
seed: 1
k: 10
k_start: -1
k_end: -1
results_dir: ./results
split_dir: split
log_data: false
testing: false
early_stopping: false
opt: adam
drop_out: false
bag_loss: ce
model_type: clam_sb
exp_code: exp
weighted_sample: false
model_size: small
task: task_1_tumor_vs_normal
csv: dataset_csv/label.csv

# CLAM specific options
no_inst_cluster: false
inst_loss: null
subtyping: true
bag_weight: 0.7
B: 8
